### ISSUE TITLE
Android Native - Settings Popup

### ISSUE THREAD

**Issue by SomehowInteractive** [StansAssets/com.stansassets.android-native--public#20]
Hello, as already discussed via mail it would be great to have the API command for google services that opens the google settings popup.

https://developers.google.com/android/reference/com/google/android/gms/games/GamesClient#getSettingsIntent()

It would be also great to get access to the Googles GamesClient instance somehow, to directly call googles api directly.

Thanks an best regards,
Luke

**Comment by stan-osipov** [comment]
Implemented & available from `2020.8`:
https://github.com/StansAssets/com.stansassets.android-native/wiki/Android-Games-Settings-Intent
