### ISSUE TITLE
Time Picker

### ISSUE THREAD

**Issue by RHamers** [StansAssets/com.stansassets.android-native--public#21]
The android native plugin includes a `DatePicker` but is missing a `TimePicker`.  The iOS version of this asset includes both so it would be very nice for them to both offer the same functionality. 

[TimePicker API](https://developer.android.com/reference/android/widget/TimePicker).

The time picker will look something like this:

![image](https://user-images.githubusercontent.com/5636895/87543947-e7423200-c6a5-11ea-8d30-3ebee712084b.png)

Thank you.

**Comment by kostiantyn-koretskyi** [comment]
Done. Will be available in following release
