### ISSUE TITLE
WheelPickerDialog Unusable

### ISSUE THREAD

**Issue by fillmore-admin** [StansAssets/com.stansassets.android-native--public#23]
Because you can't tell the difference between scrolling, clicking OK, and clicking cancel, the successful event is fired before the user even makes a selection.

For example:
```
AN_WheelPickerDialog picker = new AN_WheelPickerDialog( ... );
picker.Show( … );
```

You get a callback no matter what. The was you did the code on iOS was PERFECT.
iOS:
`private static void iOSWheelCallback(ISN_UIWheelPickerResult result) { ... }`

And you can tell what's happening:
```
result.State == ISN_UIWheelPickerStates.Done
result.State == ISN_UIWheelPickerStates.InProgress
result.State == ISN_UIWheelPickerStates.Canceled
```

Please do this again for Android, when you do the cross platform plugin, you could use the same enum:

```
using SA.CrossPlatform.UI; // or something
result.State == UM_WheelPickerStates.Done
```

**Comment by stan-osipov** [comment]
hey, @fillmore-admin this is finally fixed. The WheelPicker behavior is now the same as iOS one:
https://github.com/StansAssets/com.stansassets.android-native/wiki/Wheel-Picker-Dialog

Also, Ultimate Plugin has the same API now:
https://github.com/StansAssets/com.stansassets.ultimate-mobile/wiki/Wheel-Picker-Dialog
