### ISSUE TITLE
Camera sample not work on android 10

### ISSUE THREAD

**Issue by pcutile** [StansAssets/com.stansassets.android-native--public#30]
Compiling your sample it not work anymore on android 10

**Comment by stan-osipov** [comment]
Can you give me more info, please?
I just tried it and seem to work fine for me on 10 QKQ1.19

**Comment by stan-osipov** [comment]
Fixed.
Looks like I missed adding Camera permission into the manifest.

**Comment by nedhaljalali** [comment]
hmm..
 i have this prublem in
- Ultimate mobile pro and  Android Native pro

i am testing the (AAN_CameraAdGalleryExample) in poth ( Ultimate mobile pro & Android Native pro)

- if i click (captureAdvanced button) it say "Filed:  User denied permission."
in device and in editor.
-------------------------------------
Filed:  User denied permission.
UnityEngine.Debug:Log(Object)
AN_CameraAdGalleryExample:PrintCaptureResult(AN_CameraCaptureResult) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Samples/AppExamples/CameraAdGalleryExample/AN_CameraAdGalleryExample.cs:159)
AN_CameraAdGalleryExample:<Awake>b__10_6(AN_CameraCaptureResult) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Samples/AppExamples/CameraAdGalleryExample/AN_CameraAdGalleryExample.cs:58)
SA.Android.Camera.<>c__DisplayClass1_0:<CaptureImage>b__0(Boolean) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Runtime/API/Camera/AN_Camera.cs:37)
SA.Android.App.AN_PermissionsUtility:TryToResolvePermission(AMM_ManifestPermission[], Action`1) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Runtime/API/App/Permissions/AN_PermissionsUtility.cs:48)
SA.Android.Camera.AN_Camera:CaptureImage(Int32, Action`1) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Runtime/API/Camera/AN_Camera.cs:30)
AN_CameraAdGalleryExample:<Awake>b__10_0() (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Samples/AppExamples/CameraAdGalleryExample/AN_CameraAdGalleryExample.cs:56)
UnityEngine.EventSystems.EventSystem:Update() (at D:/ProgramfilesD/AllUnityEditerNJ2/2019.4.15f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)
--------------------------------------------------------------------
- if i click (Save screenshot) it is not working ,, and after i searching the net
i found that if i added this to manifist :
application android:requestLegacyExternalStorage="true"
and the (Save screenshot) is working fine.
- if click (getPictures) not working.



this is screen shot for my sitting.
![1](https://user-images.githubusercontent.com/75408303/102737021-6293c800-4357-11eb-85f0-fa6731e16ba1.jpg)
![2](https://user-images.githubusercontent.com/75408303/102737033-6889a900-4357-11eb-9828-e0300e8166cf.jpg)
