### ISSUE TITLE
AAN_CameraAdGalleryExample "Filed: User denied permission."

### ISSUE THREAD

**Issue by nedhaljalali** [StansAssets/com.stansassets.android-native--public#31]
i try to test ((AAN_CameraAdGalleryExample))

1- if i click (captureAdvanced button) it say "Filed: User denied permission."
in device and in editor.
log :
Filed: User denied permission.
UnityEngine.Debug:Log(Object)
AN_CameraAdGalleryExample:PrintCaptureResult(AN_CameraCaptureResult) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Samples/AppExamples/CameraAdGalleryExample/AN_CameraAdGalleryExample.cs:159)
AN_CameraAdGalleryExample:b__10_6(AN_CameraCaptureResult) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Samples/AppExamples/CameraAdGalleryExample/AN_CameraAdGalleryExample.cs:58)
SA.Android.Camera.<>c__DisplayClass1_0:b__0(Boolean) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Runtime/API/Camera/AN_Camera.cs:37)
SA.Android.App.AN_PermissionsUtility:TryToResolvePermission(AMM_ManifestPermission[], Action1) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Runtime/API/App/Permissions/AN_PermissionsUtility.cs:48) SA.Android.Camera.AN_Camera:CaptureImage(Int32, Action1) (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Runtime/API/Camera/AN_Camera.cs:30)
AN_CameraAdGalleryExample:b__10_0() (at Assets/Plugins/StansAssets/NativePlugins/AndroidNativePro/Samples/AppExamples/CameraAdGalleryExample/AN_CameraAdGalleryExample.cs:56)
UnityEngine.EventSystems.EventSystem:Update() (at D:/ProgramfilesD/AllUnityEditerNJ2/2019.4.15f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)
========================================================
========================================================
![1](https://user-images.githubusercontent.com/75408303/102753438-5706c800-437c-11eb-9b4b-c992f97b0b0e.jpg)
![2](https://user-images.githubusercontent.com/75408303/102753445-5a01b880-437c-11eb-9b97-36a7d023d7b4.jpg)

2- if i click (Save screenshot button) it is not working ,, 
and after i searching the net
i found that if i added this to manifist it will work fine :
application android:requestLegacyExternalStorage="true"

3- all other buttons not working in device.

**Comment by stan-osipov** [comment]
Hey. Look likes this is related to this issue.
https://github.com/StansAssets/com.stansassets.android-native/issues/34

Please reopen if that won't help.
