### ISSUE TITLE
Typo in AN_Camera.cs causes unintended "User denied permission." error.

### ISSUE THREAD

**Issue by LosoncziTamas** [StansAssets/com.stansassets.android-native--public#34]
Steps to reproduce:
- Setup a project that uses the Camera API.
- Grant the appropriate permissions.
- Call `CaptureImage(int maxSize, Action<AN_CameraCaptureResult> callback)`

Expected result:
- If permissions are granted the app switches to the camera.

Actual result:
- The callback returns with an error saying "User denied permission."

I found that the issue was caused by a missing negation in an if statement:
```csharp
        public static void CaptureImage(int maxSize, Action<AN_CameraCaptureResult> callback)
        {
            AN_PermissionsUtility.TryToResolvePermission(
                CameraApiCameraApiRequiredPermissions,
                granted =>
                {
                    if (granted)
                    {
                        var result = new AN_CameraCaptureResult(new SA_Error(9, "User denied permission."));
                        callback.Invoke(result);
                        return;
                    }
             //...
```

I'm using Android Native version 2020.10.2.

**Comment by stan-osipov** [comment]
Thx for the report! Fixed.
