### ISSUE TITLE
Local notification is not shown

### ISSUE THREAD

**Issue by Ardito** [StansAssets/com.stansassets.android-native--public#36]
Hello everyone,
When my application is in the background I receive local notifications, while if my application is killed, or the internet connection is turned off, I no longer receive local notifications.
If I subsequently activate my internet connection, I get local notifications even if my application has been killed.

I use "Ultimate Mobile Pro", my current code:
`

        string channelId = "my_channel_id";
        string name = "My Channel Name";
        string description = "My Channel Description";
        var importance = AN_NotificationManager.Importance.DEFAULT;

        AN_NotificationChannel channel = new AN_NotificationChannel(channelId, name, importance);
        channel.Description = description;
        
        // you can check if channel exists before re-recreating it
        AN_NotificationManager.CreateNotificationChannel(channel);

        var builder = new AN_NotificationCompat.Builder();
        builder.SetChanelId(channelId);
        builder.SetContentText(title);
        builder.SetContentTitle(body);
        builder.SetSmallIcon("android_icon_1");

        //var notification = builder.Build();
        //AN_NotificationManager.Notify(notification); //Notify doesn't exist!!

        var trigger = new AN_AlarmNotificationTrigger();
        trigger.SetDate(TimeSpan.FromSeconds(seconds));

        var request = new AN_NotificationRequest(requestID, builder, trigger);
        AN_NotificationManager.Schedule(request);
    `

Thanks for the attention

**Comment by Ardito** [comment]
Hi,
is it possible to get help? @stan-osipov

**Comment by Ardito** [comment]
UPDATE: I have discovered that the problem is not your Plugin, but the Operating System of Redmi Note 9 Pro.

**Comment by stan-osipov** [comment]
Sorry for slow replay, but I happy to see you found the root of the problem.
