### ISSUE TITLE
Ultimate-mobile with empty project, gradle error: The minSdk version can not be specified in the AndroidManifest.xml file

### ISSUE THREAD

**Issue by imoegirl** [StansAssets/com.stansassets.android-native--public#40]
![image](https://user-images.githubusercontent.com/57443542/114142631-c31a3580-9945-11eb-8ead-6cd1c831b939.png)

**Comment by Jroch4** [comment]
Also having this issue; still waiting for response from the devs (i've tryed to contact them 10+times, it has been 2 months, no response).

**Comment by Jroch4** [comment]
just tryed again with latest update of February and seems like i'm not having the issue anymore

**Comment by marfolog** [comment]
I have the same problem and this asset come several features for my app. I have to find other asses. It is very unfortunate. it happend when tou want build your app to android.

**Comment by stan-osipov** [comment]
This is fixed already and will be part of the `2020.2` release.
